spring.application.name=notification-service
server.port=8087
spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/notification_db?options=-c%20TimeZone=UTC
spring.datasource.username=staysphere
spring.datasource.password=staysphere

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
jwt.secret=ThisIsAReallyLongSecretKeyForStaySphereJwtAuth123456789
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.staysphere.notification_service.event.BookingCreatedEvent

kafka.topic.booking-events=booking-events
kafka.topic.payment-events=payment-events
kafka.topic.review-events=review-events
