spring.application.name=payment-service
server.port=8085
spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/payment_db
spring.datasource.username=staysphere
spring.datasource.password=staysphere
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
jwt.secret=ThisIsAReallyLongSecretKeyForStaySphereJwtAuth123456789