spring.application.name=payment-service
server.port=8085
spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/payment_db
spring.datasource.username=staysphere
spring.datasource.password=staysphere
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
jwt.secret=ThisIsAReallyLongSecretKeyForStaySphereJwtAuth123456789
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.topic.payment-events=payment-events
