spring.application.name=search-service
server.port=8083
spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/search_db?options=-c%20TimeZone=UTC
spring.datasource.username=staysphere
spring.datasource.password=staysphere

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
